name: base58
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/litaoh/base58

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  base_x: ^2.0.0

dev_dependencies:
  hex: ^0.2.0
  pedantic: ^1.8.0
  test: ^1.6.0
