name: bs58
description: Dart package to compute base 58 encoding. This encoding is typically used for crypto currencies such as Bitcoin.
version: 1.0.2
homepage: https://github.com/litaoh/base58
repository: https://github.com/litaoh/base58
issue_tracker: https://github.com/litaoh/base58/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  base_x: ^2.0.0

dev_dependencies:
  hex: ^0.2.0
  pedantic: ^1.8.0
  test: ^1.6.0
